jobs:
  include:
    # Focal
    - stage: "Linux, Focal, AMD64"
      os: linux
      dist: focal
      arch: amd64
      env : CONFIG=
      #    - stage: "Linux, Focal, AMD64"
      #      os: linux
      #      dist: focal
      #      arch: amd64
      #      env : CONFIG=mainnet
    - stage: "Linux, Focal, AMD64"
      os: linux
      dist: focal
      arch: amd64
      env : CONFIG=betanet
    - stage: "Linux, Focal, AMD64"
      os: linux
      dist: focal
      arch: amd64
      env : CONFIG=testnet
    - stage: "Linux, Focal, AMD64"
      os: linux
      dist: focal
      arch: amd64
      env : CONFIG=devnet
    - stage: "Linux, Focal, AMD64"
      os: linux
      dist: focal
      arch: amd64
      env : CONFIG=dev
    - stage: "Linux, Focal, AMD64"
      os: linux
      dist: focal
      arch: amd64
      env : CONFIG=beta
    - stage: "Linux, Focal, AMD64"
      os: linux
      dist: focal
      arch: amd64
      env : CONFIG=release
    - stage: "Linux, Focal, AMD64"
      os: linux
      dist: focal
      arch: amd64
      env : CONFIG=nightly

    # Bionic
    - stage: "Linux, Bionic, AMD64"
      os: linux
      dist: bionic
      arch: amd64
      env : CONFIG=
      #    - stage: "Linux, Bionic, AMD64"
      #      os: linux
      #      dist: bionic
      #      arch: amd64
      #      env : CONFIG=mainnet
    - stage: "Linux, Bionic, AMD64"
      os: linux
      dist: bionic
      arch: amd64
      env : CONFIG=betanet
    - stage: "Linux, Bionic, AMD64"
      os: linux
      dist: bionic
      arch: amd64
      env : CONFIG=testnet
    - stage: "Linux, Bionic, AMD64"
      os: linux
      dist: bionic
      arch: amd64
      env : CONFIG=devnet
    - stage: "Linux, Bionic, AMD64"
      os: linux
      dist: bionic
      arch: amd64
      env : CONFIG=dev
    - stage: "Linux, Bionic, AMD64"
      os: linux
      dist: bionic
      arch: amd64
      env : CONFIG=beta
    - stage: "Linux, Bionic, AMD64"
      os: linux
      dist: bionic
      arch: amd64
      env : CONFIG=release
    - stage: "Linux, Bionic, AMD64"
      os: linux
      dist: bionic
      arch: amd64
      env : CONFIG=nightly

    # Xenial
    - stage: "Linux, Xenial, AMD64"
      os: linux
      dist: xenial
      arch: amd64
      env : CONFIG=
      #    - stage: "Linux, Xenial, AMD64"
      #      os: linux
      #      dist: xenial
      #      arch: amd64
      #      env : CONFIG=mainnet
    - stage: "Linux, Xenial, AMD64"
      os: linux
      dist: xenial
      arch: amd64
      env : CONFIG=betanet
    - stage: "Linux, Xenial, AMD64"
      os: linux
      dist: xenial
      arch: amd64
      env : CONFIG=testnet
    - stage: "Linux, Xenial, AMD64"
      os: linux
      dist: xenial
      arch: amd64
      env : CONFIG=devnet
    - stage: "Linux, Xenial, AMD64"
      os: linux
      dist: xenial
      arch: amd64
      env : CONFIG=dev
    - stage: "Linux, Xenial, AMD64"
      os: linux
      dist: xenial
      arch: amd64
      env : CONFIG=beta
    - stage: "Linux, Xenial, AMD64"
      os: linux
      dist: xenial
      arch: amd64
      env : CONFIG=release
    - stage: "Linux, Xenial, AMD64"
      os: linux
      dist: xenial
      arch: amd64
      env : CONFIG=nightly

services:
  - docker

script:
  - ./sandbox up -v $CONFIG
