version: '3'

services:
  algod-pyteal:
    build:
      context: .
      dockerfile: ./images/algod/Dockerfile
      args:
        CHANNEL: "${CHANNEL:-stable}"
        URL: "${ALGOD_URL}"
        BRANCH: "${BRANCH}"
        SHA: "${SHA}"
        BOOTSTRAP_URL: "${BOOTSTRAP_URL}"
        GENESIS_FILE: "${GENESIS_FILE}"
        TEMPLATE: "${TEMPLATE}"
        TOKEN: "${TOKEN:-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}"
        ALGOD_PORT: ${ALGOD_PORT:-4001}
        KMD_PORT: ${KMD_PORT:-4002}
        ALGO_UID: ${ALGO_UID}
        ALGO_GID: ${ALGO_GID}
    ports:
      - ${ALGOD_PORT:-4001}:${ALGOD_PORT:-4001}
      - ${KMD_PORT:-4002}:${KMD_PORT:-4002}
      - ${CDT_PORT:-9392}:9392
    user: ${ALGO_UID}:${ALGO_GID}
    volumes:
      - ${WORKSPACE_MOUNT}:/home/algo/workspace
    working_dir: /home/algo/workspace

  indexer:
    build:
      context: .
      dockerfile: ./images/indexer/Dockerfile
      args:
        URL: "${INDEXER_URL:-https://github.com/algorand/indexer}"
        BRANCH: "${INDEXER_BRANCH:-master}"
        SHA: "${INDEXER_SHA}"
    ports:
      - ${INDEXER_PORT:-8980}:${INDEXER_PORT:-8980}
    restart: unless-stopped
    environment:
      DISABLED: "${INDEXER_DISABLED}"
      PORT: "${INDEXER_PORT:-8980}"
      SNAPSHOT: ""
      CONNECTION_STRING: "host=indexer-db port=5432 user=algorand password=algorand dbname=indexer_db sslmode=disable"
      ALGOD_ADDR: "algod-pyteal:${ALGOD_PORT:-4001}"
      ALGOD_TOKEN: ${TOKEN:-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}
    depends_on:
      - indexer-db
      - algod-pyteal

  indexer-db:
    image: "postgres:13-bullseye"
    expose:
      - 5432
    user: postgres
    environment:
      POSTGRES_USER: algorand
      POSTGRES_PASSWORD: algorand
      POSTGRES_DB: indexer_db
