version: '3'

services:
  algod:
    container_name: "${ALGOD_CONTAINER:-algorand-sandbox-algod}"
    build:
      context: .
      dockerfile: ./images/algod/Dockerfile
      args:
        CHANNEL: "stable"
        URL: ""
        BRANCH: ""
        SHA: ""
        BOOTSTRAP_URL: ""
        GENESIS_FILE: ""
        TEMPLATE: "images/algod/template.json"
        NETWORK_NUM_ROUNDS: "300000"
        NODE_ARCHIVAL: ""
        TOKEN: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
        ALGOD_PORT: "4001"
        KMD_PORT: "4002"
        CDT_PORT: "9392"
        ALGOD_FOLLOWER_PORT: "3999"
    ports:
      - 4001:4001
      - 4002:4002
      - 9392:9392
      - 3999:3999

