version: 2.1

parameters:
  ubuntu_focal_machine:
    type: string
    default: 'ubuntu-2004:202111-02'
  ubuntu_jammy_machine:
    type: string
    default: 'ubuntu-2204:2022.04.1'

workflows:
  circleci_build_and_test:
    jobs:
      - spin_up:
          name: 'spin_up_<< matrix.config >>_<< matrix.machine >>'
          matrix:
            parameters:
              config: ['', 'betanet', 'testnet', 'devnet', 'dev', 'beta', 'release', 'nightly']
              machine: [<< pipeline.parameters.ubuntu_focal_machine >>, << pipeline.parameters.ubuntu_jammy_machine >>]

jobs:
  spin_up:
    parameters:
      config:
        type: string
      machine:
        type: string
    machine:
      image: << parameters.machine >>
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install docker
          command: |
            sudo apt update
            sudo apt -y install ca-certificates curl gnupg lsb-release
            sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
            sudo echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
              $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt update
            sudo apt -y install docker-ce docker-ce-cli containerd.io
      - run:
          name: CircleCI docker download fix
          command: sudo iptables -I INPUT -m conntrack --ctstate INVALID -j DROP
      - run:
          name: Stand up sandbox
          # We should remove the no_output_timeout rule once we find a way to
          # stop generating 3 million keys for the private network.
          no_output_timeout: 30m
          environment:
            CONFIG: << parameters.config >>
          command: |
            set -e
            ./sandbox up -v $CONFIG
